/*
 * MIT License
 *
 * Copyright (c) 2021-2024 Vankka
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package dev.vankka.dependencydownload;

import com.google.errorprone.annotations.CheckReturnValue;
import dev.vankka.dependencydownload.dependency.Dependency;
import dev.vankka.dependencydownload.path.CleanupPathProvider;
import dev.vankka.dependencydownload.path.DependencyPathProvider;
import dev.vankka.dependencydownload.path.DirectoryDependencyPathProvider;
import dev.vankka.dependencydownload.relocation.Relocation;
import dev.vankka.dependencydownload.resource.DependencyDownloadResource;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.net.URL;
import java.nio.file.Path;
import java.util.*;

/**
 * An application level dependency manager to prevent loading in the same dependency multiple times.
 */
@SuppressWarnings("unused") // API
public class ApplicationDependencyManager {

    private final DependencyManager dependencyManager;

    /**
     * Creates a {@link ApplicationDependencyManager}, uses the {@link DirectoryDependencyPathProvider}.
     * @param dependencyDirectory the directory used for downloaded and relocated dependencies.
     * @see DirectoryDependencyPathProvider
     */
    public ApplicationDependencyManager(@NotNull Path dependencyDirectory) {
        this(new DirectoryDependencyPathProvider(dependencyDirectory));
    }

    /**
     * Creates a {@link ApplicationDependencyManager}.
     * @param dependencyPathProvider the dependencyPathProvider used for downloaded and relocated dependencies
     */
    public ApplicationDependencyManager(@NotNull DependencyPathProvider dependencyPathProvider) {
        this.dependencyManager = new DependencyManager(dependencyPathProvider);
    }

    /**
     * Adds the provided relocations to this {@link ApplicationDependencyManager},
     * they will be used in all {@link DependencyManager}s created by this manager after being added.
     * @param relocations the relocations to add
     * @see #addRelocation(Relocation)
     */
    public ApplicationDependencyManager addRelocations(@NotNull Relocation... relocations) {
        return addRelocations(Arrays.asList(relocations));
    }

    /**
     * Adds the provided relocations to this {@link ApplicationDependencyManager},
     * they will be used in all {@link DependencyManager}s created by this manager after being added.
     * @param relocations the relocations to add
     * @see #addRelocation(Relocation)
     */
    public ApplicationDependencyManager addRelocations(@NotNull Collection<Relocation> relocations) {
        synchronized (dependencyManager) {
            dependencyManager.addRelocations(relocations);
        }
        return this;
    }

    /**
     * Adds the provided relocation to this {@link ApplicationDependencyManager},
     * it will be used in all {@link DependencyManager}s created by this manager after being added.
     * @param relocation the relocation
     * @see #addRelocations(Collection)
     */
    public ApplicationDependencyManager addRelocation(@NotNull Relocation relocation) {
        synchronized (dependencyManager) {
            dependencyManager.addRelocation(relocation);
        }
        return this;
    }

    /**
     * Includes the dependencies and relocations from the dependency resource generated
     * by the gradle plugin, located by the provided {@link URL}.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param resourceURL the url to the resource generated by the gradle plugin
     * @return the {@link DependencyManager} to load in the dependencies
     * @throws IOException if reading the file from the {@link URL} fails
     */
    @CheckReturnValue
    public DependencyManager includeResource(@NotNull URL resourceURL) throws IOException {
        DependencyDownloadResource resource = new DependencyDownloadResource(resourceURL);
        return includeResource(resource);
    }

    /**
     * Includes the dependencies and relocations from the dependency resource generated
     * by the gradle plugin, provided as the {@link String} content of the resource.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param resourceContent the full contents of the resource generated by the gradle plugin
     * @return the {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager includeResource(@NotNull String resourceContent) {
        DependencyDownloadResource resource = new DependencyDownloadResource(resourceContent);
        return includeResource(resource);
    }

    /**
     * Includes the dependencies and relocations from the dependency resource generated
     * by the gradle plugin, provided as a list of lines from the resource.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param resourceLines all the lines of the resource generated by the gradle plugin
     * @return the {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager includeResource(@NotNull List<String> resourceLines) {
        DependencyDownloadResource resource = new DependencyDownloadResource(resourceLines);
        return includeResource(resource);
    }

    /**
     * Includes the dependencies and relocations from the {@link DependencyDownloadResource} provided as an argument.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param resource the resource to get dependencies and relocations from
     * @return the {@link DependencyManager} to load in the dependencies
     */
    public DependencyManager includeResource(@NotNull DependencyDownloadResource resource) {
        return include(resource.getDependencies(), resource.getRelocations());
    }

    /**
     * Includes the provided dependencies and relocations.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param dependencies the dependencies to include
     * @param relocations the relocations to include
     * @return the {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager include(@NotNull List<Dependency> dependencies, @NotNull List<Relocation> relocations) {
        addRelocations(relocations);
        return include(dependencies);
    }

    /**
     * Includes the provided dependencies.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param dependencies the dependencies to include
     * @return the {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager include(@NotNull Dependency... dependencies) {
        return include(Arrays.asList(dependencies));
    }

    /**
     * Includes the provided dependencies.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param dependencies the dependencies to include
     * @return the {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager include(@NotNull Collection<Dependency> dependencies) {
        dependencies = addMissingDependencies(dependencies);

        DependencyManager manager = new DependencyManager(dependencyManager.getDependencyPathProvider());
        manager.addDependencies(dependencies);
        synchronized (this.dependencyManager) {
            dependencyManager.addRelocations(this.dependencyManager.getRelocations());
        }
        return manager;
    }

    /**
     * Includes the dependencies and relocations from the provided {@link DependencyManager}, the {@link DependencyPathProvider} will be preserved.
     * <p>
     * The returned {@link DependencyManager} will only include dependencies that have not been downloaded yet,
     * and will include all the relocations from this manager.
     *
     * @param manager the manager to get dependencies and relocations from
     * @return a new {@link DependencyManager} to load in the dependencies
     */
    @CheckReturnValue
    public DependencyManager include(@NotNull DependencyManager manager) {
        addRelocations(manager.getRelocations());
        List<Dependency> dependencies = addMissingDependencies(manager.getDependencies());

        DependencyManager dependencyManager = new DependencyManager(manager.getDependencyPathProvider());
        dependencyManager.addDependencies(dependencies);
        synchronized (this.dependencyManager) {
            dependencyManager.addRelocations(this.dependencyManager.getRelocations());
        }
        return dependencyManager;
    }

    /**
     * Gets the {@link Path} where the given {@link Dependency} will be stored once downloaded.
     *
     * @param dependency the dependency.
     * @param relocated if the path should be for the relocated or unrelocated file of the Dependency
     * @return the path for the dependency
     */
    @NotNull
    public Path getPathForDependency(@NotNull Dependency dependency, boolean relocated) {
        synchronized (dependencyManager) {
            return dependencyManager.getPathForDependency(dependency, relocated);
        }
    }

    /**
     * Gets {@link Path}s to all {@link Dependency Dependencies} in this {@link ApplicationDependencyManager},
     * optionally also including the relocated paths if {@code includeRelocated} is set to {@code true}.
     * @param relocated relocated paths, otherwise unrelocated paths
     * @return paths to all dependencies, original or relocated
     * @see #getPathForDependency(Dependency, boolean)
     */
    @NotNull
    public Set<Path> getPaths(boolean relocated) {
        synchronized (dependencyManager) {
            return dependencyManager.getPaths(relocated);
        }
    }

    /**
     * Gets {@link Path}s to all {@link Dependency Dependencies} in this {@link ApplicationDependencyManager},
     * optionally also including the relocated paths if {@code includeRelocated} is set to {@code true}.
     * @param includeRelocated if relocated paths should also be included
     * @return paths to all dependencies (and optionally relocated dependencies)
     * @see #getPathForDependency(Dependency, boolean)
     */
    @NotNull
    public Set<Path> getAllPaths(boolean includeRelocated) {
        synchronized (dependencyManager) {
            return dependencyManager.getAllPaths(includeRelocated);
        }
    }

    /**
     * Removes files that are not known dependencies of this {@link DependencyManager} from {@link CleanupPathProvider#getPathsForAllStoredDependencies()} implementation.
     * <b>
     * This only accounts for dependencies that are included in this {@link DependencyManager} instance!
     * </b>
     *
     * @throws IOException if listing files in the cache directory or deleting files in it fails
     * @throws IllegalStateException if this DependencyManager's dependencyPathProvider isn't an instance of {@link CleanupPathProvider}
     * @see CleanupPathProvider
     */
    public void cleanupCacheDirectory() throws IOException, IllegalStateException {
        synchronized (dependencyManager) {
            dependencyManager.cleanupCacheDirectory();
        }
    }

    private List<Dependency> addMissingDependencies(Collection<Dependency> old) {
        List<Dependency> missingDependencies = new ArrayList<>(old.size());
        for (Dependency dependency : old) {
            String group = dependency.getGroupId();
            String artifact = dependency.getArtifactId();

            synchronized (dependencyManager) {
                // Check that there is no dependency with the same group + artifact id
                boolean noMatch = dependencyManager.getDependencies().stream()
                        .noneMatch(dep -> dep.getGroupId().equals(group)
                                && dep.getArtifactId().equals(artifact));

                if (noMatch) {
                    missingDependencies.add(dependency);
                    dependencyManager.addDependency(dependency);
                }
            }
        }
        return missingDependencies;
    }

}
